train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: /home/user/Warehouse/DIV2K_train_HR
      repeat: 20
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled-fast
    args:
      inp_size: 48
      scale_max: 4
      augment: true
  batch_size: 16

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: /home/user/Warehouse/DIV2K_valid_HR
      first_k: 10
      repeat: 160
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled-fast
    args:
      inp_size: 48
      scale_max: 4
  batch_size: 16

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: linf
  args:
    encoder_spec:
      name: edsr-baseline
      args:
        no_upsampling: true
    imnet_spec:
      name: flow
      args:
        name: flow
    flow_layers: 10
    num_layer: 3
    hidden_dim: 256

optimizer:
  name: adam
  args:
    lr: !!float 1e-4

epoch_max: 2000

# fine-tune options
fine-tune: true # turn on this flag to set fine-tune lr
fine_tune_lr: !!float 5e-5

# update each loss separately
sep: true

multi_step_lr: 
  milestones: [1200, 1400, 1600, 1800]
  gamma: 0.5

loss_weight:
  nll: !!float 5e-4
  pixel: !!float 1
  vgg: !!float 0

epoch_val: 1
epoch_save: 50

resume: ./save/edsr/epoch-last.pth